name = "kryvlabs-api"
main = "index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "kryvlabs-db"
database_id = "ff4cdf24-63d6-4b13-96af-4bf49688edeb"

[vars]
KRIYEX_URL = "https://kriyex.kryv.network"
